All workflows
Filter workflow runs
Showing runs from all workflows
7 workflow runs
Implement CI/CD for Al.just Táxi APK build
Build Al.just Táxi APK #7: Commit d464c33 pushed by compradormanv-glitch
main	
1 minute ago
 34s
Fix missing newline at end of index.html
Build Al.just Táxi APK #6: Commit cdd9055 pushed by compradormanv-glitch
main	
3 minutes ago
 27s
Refactor HTML structure and improve layout
Build Al.just Táxi APK #5: Commit 31b864f pushed by compradormanv-glitch
main	
11 minutes ago
 1m 14s
Add files via upload
Build Al.just Táxi APK #4: Commit 8b5eb7a pushed by compradormanv-glitch
main	
20 minutes ago
 33s
Add files via upload
Build Al.just Táxi APK #3: Commit 9c49f5c pushed by compradormanv-glitch
main	
24 minutes ago
 1m 1s
Add files via upload
Build Al.just Táxi APK #2: Commit 2741f9f pushed by compradormanv-glitch
main	
Today at 09:01
 45s
Add GitHub Actions workflow for building APK
Build Al.just Táxi APK #1: Commit 6a51f6f pushed by compradormanv-glitch
main	
Sep 21, 20:38 GMT+1
 1m 18s
